In [1]:
import numpy as np
import matplotlib.pyplot as plt
import csv
import pandas as pd
import datetime
import math
import random

%matplotlib inline

In [44]:
measurements = [1, 2, 3]

x = np.array([[0.], [0.]]) # initial state (location and velocity)
P = np.array([[1000., 0.], [0., 1000.]]) # initial uncertainty
u = np.array([[0.], [0.]]) # external motion
F = np.array([[1., 1.], [0, 1.]]) # next state function
H = np.array([[1., 0.]]) # measurement function
R = np.array([[1.]]) # measurement uncertainty
I = np.array([[1., 0.], [0., 1.]]) # identity matrix




In [64]:
kc = np.array([[3],[4]])
ha = np.array([[1,2]])

print(kc)
print(ha)

print(np.dot(ha, kc))

[[3]
 [4]]
[[1 2]]
[[11]]


In [81]:

# Implement the filter function below

def kalman_filter(x, P):
    for n in range(len(measurements)):
         # measurement update
        z = np.array([[measurements[n]]])
        y = z - np.dot(H,x)
        S = np.dot(np.dot(H,P), H.transpose()) + R
        K = np.dot(np.dot(P, H.transpose()), np.linalg.inv(S))
        
        x = x + np.dot(K, y)
        P = np.dot((I - np.dot(K, H)), P)
        

        # prediction
        
        x = np.dot(F, x) + u
        P = np.dot(np.dot(F, P), F.transpose())
        
    return x,P

In [82]:
kalman_filter(x, P)

(array([[ 3.99966644],
        [ 0.99999983]]), array([[ 2.33189042,  0.99916761],
        [ 0.99916761,  0.49950058]]))